[package]
name = "fusion-worker-protocol"
version = "0.14.0"
edition = "2021"

[dependencies]
fusion-core = { path = "../fusion-core" }
fusion-placement = { path = "../fusion-placement" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
